apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500M
  hostPath:
    path: "/pg-pv/pgdata/"
