name: Go
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test -v -cover ./...
        
  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yassinechamkhi/target-onboarding-assignment:0.0.2